#!/bin/sh /etc/rc.common
# by rapistor

start() {
	ps|grep offline-monitor |grep -v "grep offline-monitor"|awk '{print $1}'|xargs kill -9
	ps|grep re_dial |grep -v "grep re_dial"|awk '{print $1}'|xargs kill -9
	/lib/pppoeup/re_dial start &
}
