#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

	begin=$(uci get pppoeup.settings.metric_begin)
	switch=$(uci get pppoeup.settings.metric_switch)
start() {
	sleep 5
	/lib/pppoeup/mwan3metric.sh  $begin  $switch /etc/config/network
}


